### ISSUE TITLE
update rxswift version

### ISSUE THREAD

**Issue by jiangmingz** [MahmoudEissa/ESNetworkManager#2]

**Comment by MahmoudEissa** [comment]
Hello @jiangmingz thank you for contributing 
As you can see **RxSwift', '~> 5'** it is required by **.podspec file**, and  this error compile error displayed because of changes in **Single** object constructor which error changed to failure.
So I would prefere to create new release which depend on **RxSwift', '~> 6'** and updating **.podspec file** too.
